// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.nacfuk.membermgt.model;

import org.nacfuk.membermgt.model.Address;

privileged aspect Address_Roo_JavaBean {
    
    public String Address.getResidentialAddress() {
        return this.residentialAddress;
    }
    
}
