// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package org.nacfuk.membermgt.model;

import org.nacfuk.membermgt.model.Name;

privileged aspect Name_Roo_JavaBean {
    
    public String Name.getFirstName() {
        return this.firstName;
    }
    
    public String Name.getLastName() {
        return this.lastName;
    }
    
}
